# Use PostgreSQL via DATABASE_URL-style env vars.
# Example: postgres://user:pass@localhost:5432/myapp_development

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: sleep_la_development

test:
  <<: *default
  database: sleep_la_test

production:
  <<: *default
  database: sleep_la_production
